#!/bin/sh
module=ws2812
device=ws2812
mode="666"
cd `dirname $0`
set -e

if grep -q '^staff:' /etc/group; then
    group="staff"
else
    group="wheel"
fi

# load module
if [ -e ${module}.ko ]; then
    echo "Loading local built file ${module}.ko"
    insmod ./$module.ko $* || exit 1
else
    echo "Local file ${module}.ko not found, attempting to modprobe"
    modprobe ${module} || exit 1
fi

# determine major device number
major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)
echo "${device} major number: ${major}"

# remove any pre-existing device
rm -f /dev/${device}

# mknod creates a device node for this device
mknod /dev/${device} c $major 0

# change group owner and permissions
chgrp $group /dev/${device}
chmod $mode /dev/${device}
